export const mockTransactions = {
  Wallets: [
    {
      id: 1,
      network: "POLYGON",
      network_name: "Polygon",
      marker: "USDC",
      value: 290,
      image: "/images/usdc.png",
      contract_address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    },

    {
      id: 2,
      network: "POLYGON",
      network_name: "Polygon",
      marker: "USDT",
      value: 900,
      image: "/images/usdt.png",
      contract_address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    },

    {
      id: 3,
      network: "CELO",
      network_name: "Celo",
      marker: "CUSD",
      value: 2000,
      image: "/images/cusd.png",
      contract_address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    },
  ],
  Transactions: [
    {
      id: 1,
      merchant: "PayPass",
      date: "1:12pm 23/05/2023",
      amount: 1500,
      type: "sent",
    },
    {
      id: 2,
      merchant: "Payant",
      date: "12:22pm 3/04/2023",
      amount: 400,
      type: "received",
    },
    {
      id: 3,
      merchant: "Payee",
      date: "2:20am 13/07/2022",
      amount: 5400,
      type: "sent",
    },
    {
      id: 1,
      merchant: "PayPass",
      date: "1:12pm 23/05/2023",
      amount: 1500,
      type: "sent",
    },
    {
      id: 2,
      merchant: "Payant",
      date: "12:22pm 3/04/2023",
      amount: 400,
      type: "received",
    },
    {
      id: 3,
      merchant: "Payee",
      date: "2:20am 13/07/2022",
      amount: 5400,
      type: "sent",
    },
    {
      id: 1,
      merchant: "PayPass",
      date: "1:12pm 23/05/2023",
      amount: 1500,
      type: "sent",
    },
    {
      id: 2,
      merchant: "Payant",
      date: "12:22pm 3/04/2023",
      amount: 400,
      type: "received",
    },
    {
      id: 3,
      merchant: "Payee",
      date: "2:20am 13/07/2022",
      amount: 5400,
      type: "sent",
    },
    {
      id: 1,
      merchant: "PayPass",
      date: "1:12pm 23/05/2023",
      amount: 1500,
      type: "sent",
    },
    {
      id: 2,
      merchant: "Payant",
      date: "12:22pm 3/04/2023",
      amount: 400,
      type: "received",
    },
    {
      id: 3,
      merchant: "Payee",
      date: "2:20am 13/07/2022",
      amount: 5400,
      type: "sent",
    },
  ],
};
